services:
  web:
    build: ./articleplatform
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn articleplatform.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "
    volumes:
      - static_volume:/app/staticfiles

    restart: unless-stopped

    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
  
  db:
    image: postgres:17.2
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
   

volumes:
  db-data:
  minio-data:
  static_volume:

networks:
  app-network: