# Generated by Django 5.0.6 on 2026-04-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
