[pytest]
DJANGO_SETTINGS_MODULE = articleplatform.settings
env =
    DB_HOST=localhost
    DB_NAME=valeradb
    DB_USER=valera
    DB_PASSWORD=passwordVALERA
    DB_PORT=5432
    AWS_S3_ENDPOINT_URL=http://localhost:9000
python_files = test_*.py